import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.utils import get_column_letter

df = pd.read_csv("superstore_clean.csv")  # generated by analyze.py
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

wb = Workbook()

# ---------- RawData sheet ----------
ws_raw = wb.active
ws_raw.title = "RawData"
cols = ["OrderID","OrderDate","Region","Province","CustomerSegment","ProductCategory",
        "ProductSubCategory","Sales","Profit","OrderQty","Discount","Year"]
raw = df[cols].copy()
raw["OrderDate"] = raw["OrderDate"].dt.strftime("%Y-%m-%d")

header_font = Font(name="Arial", bold=True, color="FFFFFF")
header_fill = PatternFill("solid", fgColor="2F5597")
for c, name in enumerate(cols, start=1):
    cell = ws_raw.cell(row=1, column=c, value=name)
    cell.font = header_font
    cell.fill = header_fill

for r, row in enumerate(raw.itertuples(index=False), start=2):
    for c, val in enumerate(row, start=1):
        ws_raw.cell(row=r, column=c, value=val)

for c in range(1, len(cols)+1):
    ws_raw.column_dimensions[get_column_letter(c)].width = 16

n_rows = len(raw) + 1  # including header

# ---------- Summary sheet ----------
ws = wb.create_sheet("Summary")
ws.sheet_view.showGridLines = False

title_font = Font(name="Arial", size=16, bold=True, color="1F4E78")
ws["B2"] = "Superstore Sales Performance Dashboard"
ws["B2"].font = title_font
ws["B3"] = "Source: Sample Superstore transactional dataset (2009-2012) | Built by Bhabanisankar Bhol"
ws["B3"].font = Font(name="Arial", italic=True, size=9, color="808080")

kpi_font = Font(name="Arial", bold=True, size=12)
label_font = Font(name="Arial", size=10, color="595959")
kpi_fill = PatternFill("solid", fgColor="D9E1F2")

def kpi_box(row, col, label, formula, numfmt):
    lcell = ws.cell(row=row, column=col, value=label)
    lcell.font = label_font
    vcell = ws.cell(row=row+1, column=col, value=formula)
    vcell.font = kpi_font
    vcell.number_format = numfmt
    for rr in (row, row+1):
        ws.cell(row=rr, column=col).fill = kpi_fill

kpi_box(5, 2, "Total Sales", f"=SUM(RawData!H2:H{n_rows})", '$#,##0')
kpi_box(5, 4, "Total Profit", f"=SUM(RawData!I2:I{n_rows})", '$#,##0')
kpi_box(5, 6, "Overall Margin %", f"=D6/B6", '0.0%')
kpi_box(5, 8, "Total Orders", f"=SUMPRODUCT(1/COUNTIF(RawData!A2:A{n_rows},RawData!A2:A{n_rows}))", '#,##0')

# --- Region table (SUMIFS-driven) ---
ws["B9"] = "Sales & Profit by Region"
ws["B9"].font = Font(name="Arial", bold=True, size=12)
regions = sorted(df["Region"].dropna().unique().tolist())
headers = ["Region", "Sales", "Profit", "Margin %"]
for c, h in enumerate(headers, start=2):
    cell = ws.cell(row=10, column=c, value=h)
    cell.font = header_font
    cell.fill = header_fill
for i, region in enumerate(regions):
    r = 11 + i
    ws.cell(row=r, column=2, value=region)
    ws.cell(row=r, column=3, value=f'=SUMIFS(RawData!$H$2:$H${n_rows},RawData!$C$2:$C${n_rows},B{r})').number_format = '$#,##0'
    ws.cell(row=r, column=4, value=f'=SUMIFS(RawData!$I$2:$I${n_rows},RawData!$C$2:$C${n_rows},B{r})').number_format = '$#,##0'
    ws.cell(row=r, column=5, value=f'=D{r}/C{r}').number_format = '0.0%'
region_last_row = 10 + len(regions)

# --- Category table ---
cat_start_col = 7
ws.cell(row=10, column=cat_start_col, value="Category").font = header_font
ws.cell(row=10, column=cat_start_col).fill = header_fill
ws.cell(row=10, column=cat_start_col+1, value="Sales").font = header_font
ws.cell(row=10, column=cat_start_col+1).fill = header_fill
ws.cell(row=10, column=cat_start_col+2, value="Profit").font = header_font
ws.cell(row=10, column=cat_start_col+2).fill = header_fill
categories = sorted(df["ProductCategory"].dropna().unique().tolist())
for i, cat in enumerate(categories):
    r = 11 + i
    ws.cell(row=r, column=cat_start_col, value=cat)
    ws.cell(row=r, column=cat_start_col+1, value=f'=SUMIFS(RawData!$H$2:$H${n_rows},RawData!$F$2:$F${n_rows},G{r})').number_format = '$#,##0'
    ws.cell(row=r, column=cat_start_col+2, value=f'=SUMIFS(RawData!$I$2:$I${n_rows},RawData!$F$2:$F${n_rows},G{r})').number_format = '$#,##0'
cat_last_row = 10 + len(categories)

# --- Charts ---
bar = BarChart()
bar.title = "Sales & Profit by Region"
bar.style = 10
bar.y_axis.title = "USD"
bar.x_axis.title = "Region"
data = Reference(ws, min_col=3, max_col=4, min_row=10, max_row=region_last_row)
cats = Reference(ws, min_col=2, min_row=11, max_row=region_last_row)
bar.add_data(data, titles_from_data=True)
bar.set_categories(cats)
bar.width, bar.height = 18, 9
ws.add_chart(bar, "B18")

pie = PieChart()
pie.title = "Sales Share by Category"
pdata = Reference(ws, min_col=cat_start_col+1, min_row=10, max_row=cat_last_row)
pcats = Reference(ws, min_col=cat_start_col, min_row=11, max_row=cat_last_row)
pie.add_data(pdata, titles_from_data=True)
pie.set_categories(pcats)
pie.width, pie.height = 12, 9
ws.add_chart(pie, "G18")

for c, w in {"B":16,"C":14,"D":14,"E":12,"G":18,"H":14,"I":14}.items():
    ws.column_dimensions[c].width = w

wb.save("Superstore_Sales_Dashboard.xlsx")
print("saved")
